language: node_js
node_js:
  - 0.11
before_install:
  - ./scripts/installTravisDeps.sh
  - ./scripts/installErizo.sh
  - ./scripts/installNuve.sh
  - ./scripts/installBasicExample.sh
  - ./scripts/initLicode.sh
  - sleep 10
  - ./scripts/initBasicExample.sh
  - ./.travis/scripts/install_chrome.sh
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
cache:
  apt: true
  directories:
  - node-modules/
  - build/